### PR TITLE
feat(marketpage): change marketDetail place in mobile and tablet

### PR DESCRIPTION
**Pull request by shmodarresi**

### CODE REVIEW

**Review by tlebon — DISMISSED** [review]
this looks generally fine but maybe we also want to think about what to do with the graph on mobile as its not very responsive and destroys the page

**Comment by tlebon** [comment]
for example: page opens like this
Screen Shot 2021-09-21 at 22 08 29

but you can zoom out to this
Screen Shot 2021-09-21 at 22 07 55

**Comment by shekhar-shubhendu** [comment]
> this looks generally fine but maybe we also want to think about what to do with the graph on mobile as its not very responsive and destroys the page

so the graph doesn't work if you are adjusting the page using the web inspector but if you open on mobile or refresh( in inspector) then it works.

**Comment by shekhar-shubhendu** [comment]
@anitasengupta should we align the market details section to the centre and under the image? I think we should.

image

**Review by shekhar-shubhendu — DISMISSED** [review]

**Review by anitasengupta — COMMENTED** [review]
@shmodarresi design review

- [x] 1. spacing between nav bar and  market phase label
- [x] 2. see revised design for market header: no image, header question 30px
- [x] 3. space between all cards: 16px (space between graph and buy/sell
- [x] 4. space between market details card + twitter share button: 40px
- [x] 5. twitter share button size: 44px
- [x] 6. include “Share” text under Twitter share button (all sizes)
- [x] 7. space between body content and footer: 120px

**Review by shekhar-shubhendu — DISMISSED** [review]

**Comment by shmodarresi** [comment]
> @shmodarresi design review
> 
> * [x]  1. spacing between nav bar and  market phase label
> * [x]  2. see revised design for market header: no image, header question 30px
> * [x]  3. space between all cards: 16px (space between graph and buy/sell
> * [x]  4. space between market details card + twitter share button: 40px
> * [x]  5. twitter share button size: 44px
> * [x]  6. include “Share” text under Twitter share button (all sizes)
> * [x]  7. space between body content and footer: 120px

**Review by shekhar-shubhendu — APPROVED** [review]

**Pull request merged**
